### ISSUE TITLE
Improve documentation and make it less error prone

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-client-electricity-trading-python#39]
### What's needed?

The current examples written in the README file are not checked by the different existent python tools in the project (pylint, mypy, etc.) and they are likely to become outdated while the code is updated.

### Proposed solution

Write examples  in the documentation of the code to make them less error-prone and always keep the docs up-to-date.
Ideally it can be done similar to the frequenz-SDK [guidelines](https://frequenz-floss.github.io/frequenz-sdk-python/v1.0-pre/user-guide/) and [tutorials](https://frequenz-floss.github.io/frequenz-sdk-python/v1.0-pre/tutorials/getting_started/). And then we could link the examples in the README if needed.

This is how documentation is written for the [actor guidelines](https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py)

**Comment by ghost** [comment]
Fixed in #52
