### ISSUE TITLE
Investigate the root cause of empty strings for price or quantity

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-client-electricity-trading-python#41]
### What happened?

Listing gridpool orders can show errors for orders with no price and/or quantity.

```txt
Failed to convert order details for order: order_id: 645998 order {delivery_area {code: "10YDE-EON------1" code_type: ENERGY_MARKET_CODE_TYPE_EUROPE_EIC} delivery_period {start {seconds: 1672531200} duration: DELIVERY_DURATION_15} type: ORDER_TYPE_LIMIT side: MARKET_SIDE_BUY execution_option: ORDER_EXECUTION_OPTION_UNSPECIFIED}state_detail {state: ORDER_STATE_CANCELED}open_quantity {mwh {value: "0"}} filled_quantity {mwh {value: "0"}} create_time {seconds: 1724168717 nanos: 892807000}modification_time {seconds: 1724168717 nanos: 931256000}
```

### What did you expect instead?

The client is already skipping orders that cannot process and logging an error. However, we need to find out the root cause of the empty string for price or quantity.

### Affected version(s)

v0.2.3

### Affected part(s)

I don't know (part:❓)

**Comment by ghost** [comment]
Upon closer examination, the orders that cause the error have their fields being `NULL`. This used to be set by the service when an order was cancelled, but should not be the case anymore (it was changed in [#85](https://github.com/frequenz-io/frequenz-service-electricity-trading/pull/85)). However these rows still exist in the table, so when `list_gridpool_order` is called on these orders it will still log the error.
