### ISSUE TITLE
Fetch subsequent paginated data on list_public_trades

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-electricity-trading-python#80]
Response data of `list_public_trades` is paginated, the client should automatically request and yield all subsequent pages for a given response. As an example can be found in a previous version of the reporting client: 
https://github.com/frequenz-floss/frequenz-client-reporting-python/blob/df5fec8050d539400cd71f5afbbf2bf7e74b7ab0/src/frequenz/client/reporting/_client.py#L258-L278

**Comment by ghost** [comment]
Done in #82
